"""make readings cols nullable

Revision ID: 8cc5838f6c47
Revises: 9adaa9d1a4ac
Create Date: 2026-05-25 10:47:04.812224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc5838f6c47'
down_revision: Union[str, Sequence[str], None] = '9adaa9d1a4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('readings', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('readings', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('readings', 'format',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('readings', 'format',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('readings', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('readings', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
